from .minsrf import SOAP_OT_MinimalSurface
from .vghard import SOAP_OT_HardenVGroup
from .vgsoft import SOAP_OT_SoftenVGroup
from .inflation import SOAP_OT_Inflation
from .selectbound import SOAP_OT_SelectBoundary
from .bake import SOAP_OT_BakeChannel
from .img2vg import SOAP_OT_ImageToVG
from .vgremap import SOAP_OT_RemapVGroup
from .mapops import SOAP_OT_OperateMaps
from .lerp import SOAP_OT_Interpolate
from .changedevice import SOAP_OT_ChangeDevice
from .cudatorch import SOAP_OT_CudaTorch
from .vgtransfer import SOAP_OT_TransferVGroup
