title: SoapTools for Blender
description: Computational design tools and utilities for Blender
theme: minima # or "jekyll-theme-cayman", "jekyll-theme-slate", etc.
markdown: GFM # GitHub-flavored markdown
